#%RAML 1.0 SecurityScheme
type: x-client-credentials
description: Custom Client Credentials Security Scheme
describedBy:
  headers:
    client_id:
      type: string
    client_secret:
      type: string